---
name: 'Setup Umka'
author: Yevhen Fabizhevskyi
description: 'This action sets up a Umka.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'Umka version.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
